// SEARCH
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH'
export const RECEIVE_SEARCH_SUCCESS = 'RECEIVE_SEARCH_SUCCESS'
export const RECEIVE_SEARCH_FAILURE = 'RECEIVE_SEARCH_FAILURE'

// PROGRAMS
export const FETCH_PROGRAMS = 'FETCH_PROGRAMS'
export const FETCH_PROGRAMS_SUCCESS = 'FETCH_PROGRAMS_SUCCESS'
export const FETCH_PROGRAMS_FAILURE = 'FETCH_PROGRAMS_FAILURE'


export const FETCH_FACILITIES = 'FETCH_FACILITIES'
export const FETCH_FACILITIES_SUCCESS = 'FETCH_FACILITIES_SUCCESS'
export const FETCH_FACILITIES_FAILURE = 'FETCH_FACILITIES_FAILURE'
