// GLOBAL
export const UPDATE_ENTITIES = 'UPDATE_ENTITIES'

// SEARCH
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH'
export const RECEIVE_SEARCH_SUCCESS = 'RECEIVE_SEARCH_SUCCESS'
export const RECEIVE_SEARCH_FAILURE = 'RECEIVE_SEARCH_FAILURE'

// PROGRAMS
export const FETCH_PROGRAMS = 'FETCH_PROGRAMS'
export const FETCH_PROGRAMS_SUCCESS = 'FETCH_PROGRAMS_SUCCESS'
export const FETCH_PROGRAMS_FAILURE = 'FETCH_PROGRAMS_FAILURE'

export const UPDATE_PROGRAMS = 'programs/UPDATE_PROGRAMS'

// FACILITIES
export const FETCH_FACILITIES = 'FETCH_FACILITIES'
export const FETCH_FACILITIES_SUCCESS = 'FETCH_FACILITIES_SUCCESS'
export const FETCH_FACILITIES_FAILURE = 'FETCH_FACILITIES_FAILURE'
export const UPDATE_FACILITIES = 'facilities/UPDATE_FACILITIES'

// MARKER
export const UPDATE_MARKERS = 'UPDATE_MARKERS'

// TABS
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
