export const APP_LOADING = 'appLoading/IS_LOADING'
export const APP_LOADED = 'appLoading/IS_LOADED'

// GLOBAL
export const UPDATE_ENTITIES = 'UPDATE_ENTITIES'

// SEARCH
export const SUBMIT_SEARCH = 'search/SUBMIT_SEARCH'
export const RECEIVE_SEARCH_SUCCESS = 'search/RECEIVE_SEARCH_SUCCESS'
export const RECEIVE_SEARCH_FAILURE = 'search/RECEIVE_SEARCH_FAILURE'

// PROGRAMS/ACTIVITIES
export const UPDATE_PROGRAMS = 'programs/UPDATE_PROGRAMS'
export const UPDATE_PROGRAM_CATEGORIES = 'programs/UPDATE_PROGRAM_CATEGORIES'

// FACILITIES/LOCATIONS
export const UPDATE_FACILITIES = 'facilities/UPDATE_FACILITIES'
export const UPDATE_FACILITY_CATEGORIES = 'facilities/UPDATE_FACILITY_CATEGORIES'

// MARKER
export const UPDATE_MARKERS = 'markers/UPDATE_MARKERS'
export const SET_MAP_MARKERS = 'markers/SET_MAP_MARKERS'
export const RESET_MARKERS = 'markers/RESET_MARKERS'

// TABS
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'

// MOBILE
export const TOGGLE_MOBILE_NAV = 'mobile/TOGGLE_MOBILE_NAV'
export const TOGGLE_MOBILE_SEARCH = 'mobile/TOGGLE_MOBILE_SEARCH'
export const SET_MOBILE_VIEW = 'mobile/SET_MOBILE_VIEW'
export const TOGGLE_MOBILE_FILTERS = 'mobile/TOGGLE_MOBILE_FILTERS'

// MODALS
export const TOGGLE_MODAL = 'modal/TOGGLE_MODAL'
export const CLOSE_MODALS = 'modal/CLOSE_MODALS'
